travis:
  secure:
    BINSTAR_TOKEN: Uqp3odhA5zLBiLnjCJMkvfJ5nyzQrvJhYk6k5JcZv8y0NMJU3blve6TX7wJxnV+JF85q72RDHBfYq+OmKvnYk0A0vhkuq1Dvd8CcUm+Co7nNyPFLN1jXPbzj5RCtoIIEyufmGOBd8MKK5UpG4HLxhggjweQRQz87yOFNfMqChcHoVHHTfNusz/u5+XzeYZWoCp3HlCgleX/nTHW5wPwqpC6DZGt6rUIJXCMc8s63T387BvtnQbUc3vRxA2gJOZmgN5eU0xfwaAdCBjSRmOplZPiWR4EYR3iIhbHRSn184hTUneokrivpXrtNjQX6UMgNpOkEkwlIBlrCy6sO3KBInPlD820gi+xaQqaW7Egz/GicxxaH5uvx4OcaYvitQVPX8p4V45ab0ZFj/Ps7d4cOoItnV98TkoLLJnJK+M/ftMPCKJqdat4QhihhhUj+tvhjIh1UuWa7eh2fUc/Y9BSyWhESyFmmx+wwNSZgU1BQGtSJ0DPYvird55s3qDicR0Yrb6jUt3EcPH0r0SpUkqv1lzV0kiQ69naOf/tLT9tGB2szumR6y0b/ASZomjPDbko5amGLmbTwJF4HGHB7m5EKIRKczb4+r8g+EXC0Pdfutt9H6PvSy+q/pLH83Qu4drWIo+6gRGZe3I+cLij9j6ECNssqPXmomzErY8bsHYx7xfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
