travis:
  secure:
    BINSTAR_TOKEN: ppwgk1prnf1+kmZ+qtegMEMvsa1yaAfgIUU2itqziQnXpm3DR89j2wSBlaBRZtaCEZR1yIz2zkZmG610LamqiEi/VzND0kjyvFe0QKCN4ZQJdoqg5Y7DDl9qd32ZZe+A6yMMps3fbN93LDinmn90NUQ0/kK3sI7yq4yvPpj3/d0cLybvdNtW0SeDrp8G7PudR34sV+nhVY9J6x5Mifch+sw5e8uAPWTIP36kOssRhyW90ZV21e0rQDY0ccV6aF4B7o5fsxjmSdUvjHqxVXrxge3PCgkiXCyTnZsXmp5H1ZVNbkvTxehlpJwwlU7vQgFT+AsHNGnVbZLPwOBLEK3Stthnvp+cMBB0VDJ92fyXE41ZCWuUC7sx4csBNyCy642Rv43VCsBxpTOYxH2xAf1vN8PhcHgJ6p4BitzvBS1rEcsHmc6uQLa/DmvXMd4tTd1phmDNVMW2JaM4hVfT2WNykBi/FL7tn+N1hwjrHFi6DknRUnwsOvrhoMszzs3MULtNvZ6J8E73WWnBRDr+2SYFqeRCwzudsw/mKN75eJV+X3rKSTq9F/fxnAjp5xKQxkqfQnCQYUXs2uJj3RY/owaR0ECmCcQM8BwABjffG4vyoBaDw0GNXvipkyvkfZ2Be1bwZZbv4BBoXUtkLdrn5AJYJQ7yN1mEc4WVwLZQPH73QnI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
